### ISSUE TITLE
Vale 3 not working with AsciiDoc and diagrams (PlantUML, Mermaid)

### ISSUE THREAD

**Issue by sedroc** [vale-cli/vale#759]
### Check for existing issues

- [X] Completed

### Environment

- macOS 14.3
- Installed via Homebrew
- vale -v
   vale version 3.0.5
- asciidoctor -v
  Asciidoctor 2.0.20 [https://asciidoctor.org]
  Runtime Environment (ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

### Describe the bug / provide steps to reproduce it

1. Take the following minimal example `index.adoc` containing a PlantUML diagram
   ```asciidoc
   = Test

   [plantuml,test1,svg]
   ----
   @startuml
   [node]
   @enduml
   ----
   ```
2. Run `vale index.adoc`
3. Get the following error message
   ```
   E100 [index.adoc] Runtime error

   E100 [index.adoc] Runtime error

   asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - undefined method `[]' for nil
     Use --trace to show backtrace


   Execution stopped with code 1.

   Execution stopped with code 1.
   ```
4. Strangely, running just `vale .` in the folder with `index.adoc` works
   ```
   ✔ 0 errors, 0 warnings and 0 suggestions in 1 file.
   ```

This issue breaks the display of vale errors in editors such as Visual Studio Code and neovim as soon as a diagram is added.

**Comment by jdkato** [comment]
I can confirm the issue. However, it works with version 2.0.18 of `asciidoctor`.

I'll need to look into what changed.
